</sys/src/ape/config
ROOT=..
<../mkfile.proto

CFLAGS=$CFLAGS -c\
	-D_PATH_SSL_CA_FILE="/sys/lib/tls/cert.pem"\
	-I../crypto/asn1\
	-I../crypto/bn\
	-I../crypto/evp\
	-I../crypto/modes

LD=pcc -lopenssl/ssl.a -lopenssl/crypto.a

CFILES=`{ls *.c}
OFILES=${CFILES:%.c=%.$O}

HFILES=\
	tls_internal.h\

LIB=/$objtype/lib/ape/libtls.a

</sys/src/cmd/mklib
