</sys/src/ape/config
ROOT=../..
<$ROOT/mkfile.proto

CFLAGS=$CFLAGS -c

OFILES=\
	explicit_bzero.$O\
	strlcat.$O\
	strlcpy.$O\
	strndup.$O\
	strnlen.$O\
	strsep.$O\
	bsd-asprintf.$O\
	freezero.$O\
	timegm.$O\
	reallocarray.$O\
	recallocarray.$O\
	syslog_r.$O\
	timingsafe_memcmp.$O\
	timingsafe_bcmp.$O\

LIB=/$objtype/lib/ape/libcrypto.a

</sys/src/cmd/mklib
