</sys/src/ape/config
ROOT=../..
<$ROOT/mkfile.proto

CFLAGS=$CFLAGS -DOPENSSL_NO_HW_PADLOCK -I.. -I../asn1 -c

CFILES=`{ls *.c}
OFILES=${CFILES:%.c=%.$O}

LIB=/$objtype/lib/ape/libcrypto.a

</sys/src/cmd/mklib
