</sys/src/ape/config
ROOT=../..
<$ROOT/mkfile.proto

CFLAGS=$CFLAGS -c

OFILES=\
	camellia.$O\
	cmll_cbc.$O\
	cmll_cfb.$O\
	cmll_ctr.$O\
	cmll_ecb.$O\
	cmll_misc.$O\
	cmll_ofb.$O\

LIB=/$objtype/lib/ape/libcrypto.a

</sys/src/cmd/mklib
