</sys/src/ape/config
ROOT=../..
<$ROOT/mkfile.proto

CFLAGS=$CFLAGS -c

OFILES=\
	aes_cbc.$O\
	aes_cbc.$O\
	aes_core.$O\
	aes_cfb.$O\
	aes_ctr.$O\
	aes_ecb.$O\
	aes_ige.$O\
	aes_misc.$O\
	aes_ofb.$O\
	aes_wrap.$O\

LIB=/$objtype/lib/ape/libcrypto.a

</sys/src/cmd/mklib
