</sys/src/ape/config
ROOT=../..
<$ROOT/mkfile.proto

CFLAGS=$CFLAGS -c

OFILES=\
	b_dump.$O\
	b_posix.$O\
	b_print.$O\
	b_sock.$O\
	bf_buff.$O\
	bf_nbio.$O\
	bf_null.$O\
	bio_cb.$O\
	bio_err.$O\
	bio_lib.$O\
	bio_meth.$O\
	bss_acpt.$O\
	bss_bio.$O\
	bss_conn.$O\
	bss_dgram.$O\
	bss_fd.$O\
	bss_file.$O\
	bss_log.$O\
	bss_mem.$O\
	bss_null.$O\
	bss_sock.$O\

LIB=/$objtype/lib/ape/libcrypto.a

</sys/src/cmd/mklib
