# GitHub Actions workflow to run tests on Android.
name: "Android"

on:
  push:
    branches: ["master", "OPENBSD_8_0", "OPENBSD_7_9", "OPENBSD_7_8"]
  pull_request: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: "Test ${{ matrix.name }}"
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Minimum API 26"
            api-level: 26
          - name: "Latest API"
            api-level: latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Install build dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: "Run CI script"
        run: |
          ANDROID_NDK_HOME="$ANDROID_NDK_LATEST_HOME" ./scripts/test
        env:
          ARCH: "android"
          ANDROID_API_LEVEL: "${{ matrix.api-level }}"
