name: android_ci

on: [push, pull_request]

jobs:
  build-android-8-9:
    runs-on: ubuntu-18.04
    continue-on-error: false
    env:
      ARCH: android
      MIN_NAL: 26
      MAX_NAL: 28
    name: Android 8.x 9
    steps:
    - uses: actions/checkout@main
    - name: Run CI script
      run: ./scripts/test

  build-android-10-11:
    runs-on: ubuntu-18.04
    continue-on-error: false
    env:
      ARCH: android
      MIN_NAL: 29
      MAX_NAL: 30
    name: Android 10 11
    steps:
    - uses: actions/checkout@main
    - name: Run CI script
      run: ./scripts/test
