name: "CIFuzz"

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  fuzz:
    name: "Fuzz"
    runs-on: "ubuntu-24.04"
    permissions:
      security-events: write
    steps:
      - name: "Build Fuzzers"
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@1b73904cfccf3addafb6d599b8e0f32e710790cc
        with:
          oss-fuzz-project-name: 'libressl'
          dry-run: false
          language: c++

      - name: "Run Fuzzers"
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@1b73904cfccf3addafb6d599b8e0f32e710790cc
        with:
          oss-fuzz-project-name: 'libressl'
          fuzz-seconds: 300
          dry-run: false
          language: c++
          output-sarif: true

      - name: "Upload Crash"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure() && steps.build.outcome == 'success'
        with:
          name: "artifacts"
          path: "./out/artifacts"

      - name: "Upload SARIF"
        uses: github/codeql-action/upload-sarif@e46ed2cbd01164d986452f91f178727624ae40d7 # v4.35.3
        if: always() && steps.build.outcome == 'success'
        with:
          sarif_file: "cifuzz-sarif/results.sarif"
          category: "cifuzz-sarif"
