name: linux_ci_asan

on: [push, pull_request]

jobs:
  build-native:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [clang]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    env:
      CC: ${{ matrix.compiler }}
      ARCH: native
      CFLAGS: "-ggdb -fsanitize=address"
      LDFLAGS: "-fsanitize=address"
      CTEST_OUTPUT_ON_FAILURE: 1
    name: ${{ matrix.compiler }} - ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
    - name: Run CI script
      run: ./scripts/test
