# GitHub Actions workflow to run tests on a Solaris VM.
name: "Solaris"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # At 00:00 daily.

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: "Solaris"
    runs-on: ubuntu-26.04
    if: ${{ github.repository_owner == 'libressl' || github.event_name != 'schedule' }}
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Setup"
        run: |
          sudo apt-get update
          sudo apt-get install -y automake autoconf libtool
          ./autogen.sh

      - name: "Build on VM"
        uses: vmactions/solaris-vm@a11f407d3720a3717673d4194f19ee63b284977e # v1.4.0
        with:
          prepare: |
            pkg install gcc make
            PERL_MM_USE_DEFAULT=1 cpan -T IO::Socket::SSL
          run: |
            perl -MIO::Socket::SSL::Utils -e 1
            MAKE=gmake ./configure
            gmake -j2 check || (cat tests/test-suite.log && exit 1)
